### ISSUE TITLE
Issue with httpx AsyncOAuth2Client

### ISSUE THREAD

**Issue by kesavkolla** [lepture/authlib#199]
Error in setting the Content-Length while fetching tokens.  Looks like the same httpx client is used with updated body but the Content-Lenght is not changed.

I'm using latest version of libs Authlib==0.14.1 httpx==0.11.1

Here is my sample code

```python
from authlib.integrations.httpx_client import AsyncOAuth2Client

config = get_settings()
token_endpoint = 'token_url'

client = AsyncOAuth2Client(config.keycloak.client_id,
                           config.keycloak.credential.get_secret_value(),
                           grant_type='client_credentials',
                           scope='offline_access profile email',
                           audience='auth',
                           token_endpoint=token_endpoint,
                           token_endpoint_auth_method='client_secret_post')
await client.fetch_token(token_endpoint)
```

Error stack trace

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "<console>", line 1, in <module>
  File "/home/kesav/.virtualenvs/smtp/lib/python3.8/site-packages/authlib/integrations/httpx_client/oauth2_client.py", line 108, in _fetch_token
    resp = await self.post(
  File "/home/kesav/.virtualenvs/smtp/lib/python3.8/site-packages/httpx/client.py", line 1305, in post
    return await self.request(
  File "/home/kesav/.virtualenvs/smtp/lib/python3.8/site-packages/authlib/integrations/httpx_client/oauth2_client.py", line 88, in request
    return await super(AsyncOAuth2Client, self).request(
  File "/home/kesav/.virtualenvs/smtp/lib/python3.8/site-packages/httpx/client.py", line 1096, in request
    response = await self.send(
  File "/home/kesav/.virtualenvs/smtp/lib/python3.8/site-packages/httpx/client.py", line 1117, in send
    response = await self.send_handling_redirects(
  File "/home/kesav/.virtualenvs/smtp/lib/python3.8/site-packages/httpx/client.py", line 1147, in send_handling_redirects
    response = await self.send_handling_auth(
  File "/home/kesav/.virtualenvs/smtp/lib/python3.8/site-packages/httpx/client.py", line 1184, in send_handling_auth
    response = await self.send_single_request(request, timeout)
  File "/home/kesav/.virtualenvs/smtp/lib/python3.8/site-packages/httpx/client.py", line 1208, in send_single_request
    response = await dispatcher.send(request, timeout=timeout)
  File "/home/kesav/.virtualenvs/smtp/lib/python3.8/site-packages/httpx/dispatch/connection_pool.py", line 157, in send
    raise exc
  File "/home/kesav/.virtualenvs/smtp/lib/python3.8/site-packages/httpx/dispatch/connection_pool.py", line 153, in send
    response = await connection.send(request, timeout=timeout)
  File "/home/kesav/.virtualenvs/smtp/lib/python3.8/site-packages/httpx/dispatch/connection.py", line 44, in send
    return await self.connection.send(request, timeout=timeout)
  File "/home/kesav/.virtualenvs/smtp/lib/python3.8/site-packages/httpx/dispatch/http11.py", line 51, in send
    await self._send_request_body(request, timeout)
  File "/home/kesav/.virtualenvs/smtp/lib/python3.8/site-packages/httpx/dispatch/http11.py", line 101, in _send_request_body
    await self._send_event(event, timeout)
  File "/home/kesav/.virtualenvs/smtp/lib/python3.8/site-packages/httpx/dispatch/http11.py", line 117, in _send_event
    bytes_to_send = self.h11_state.send(event)
  File "/home/kesav/.virtualenvs/smtp/lib/python3.8/site-packages/h11/_connection.py", line 469, in send
    data_list = self.send_with_data_passthrough(event)
  File "/home/kesav/.virtualenvs/smtp/lib/python3.8/site-packages/h11/_connection.py", line 502, in send_with_data_passthrough
    writer(event, data_list.append)
  File "/home/kesav/.virtualenvs/smtp/lib/python3.8/site-packages/h11/_writers.py", line 79, in __call__
    self.send_data(event.data, write)
  File "/home/kesav/.virtualenvs/smtp/lib/python3.8/site-packages/h11/_writers.py", line 101, in send_data
    raise LocalProtocolError("Too much data for declared Content-Length")
h11._util.LocalProtocolError: Too much data for declared Content-Length
```

**Comment by lepture** [comment]
It should be fixed by https://github.com/lepture/authlib/commit/7f4e2af155030afc6f7f1f44ebdadcaacf9a2ad5

please verify it with master code

**Comment by kesavkolla** [comment]
I used master code still not working.  This time I get Invalid client secret

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "<console>", line 1, in <module>
  File "/home/kesav/.virtualenvs/smtp/lib/python3.8/site-packages/authlib/integrations/httpx_client/oauth2_client.py", line 120, in _fetch_token
    return self.parse_response_token(resp.json())
  File "/home/kesav/.virtualenvs/smtp/lib/python3.8/site-packages/authlib/oauth2/client.py", line 348, in parse_response_token
    self.handle_error(error, description)
  File "/home/kesav/.virtualenvs/smtp/lib/python3.8/site-packages/authlib/integrations/httpx_client/oauth2_client.py", line 76, in handle_error
    raise OAuthError(error_type, error_description)
authlib.common.errors.AuthlibBaseError: unauthorized_client: Invalid client secret
```

**Comment by kesavkolla** [comment]
It works with master branch.

**Comment by cjh1** [comment]
I am seeing this with authlib=0.15.4 httpx=0.18.2

```
Traceback (most recent call last):
  File "job_worker.py", line 45, in <module>
    loop.run_until_complete(test())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "job_worker.py", line 38, in test
    token = await client.fetch_token()
  File "/home/cjh/.virtualenvs/4ddist/lib/python3.8/site-packages/authlib/integrations/httpx_client/oauth2_client.py", line 120, in _fetch_token
    resp = await self.post(
  File "/home/cjh/.virtualenvs/4ddist/lib/python3.8/site-packages/httpx/_client.py", line 1807, in post
    return await self.request(
  File "/home/cjh/.virtualenvs/4ddist/lib/python3.8/site-packages/authlib/integrations/httpx_client/oauth2_client.py", line 94, in request
    return await super(AsyncOAuth2Client, self).request(
  File "/home/cjh/.virtualenvs/4ddist/lib/python3.8/site-packages/httpx/_client.py", line 1481, in request
    response = await self.send(
  File "/home/cjh/.virtualenvs/4ddist/lib/python3.8/site-packages/httpx/_client.py", line 1568, in send
    response = await self._send_handling_auth(
  File "/home/cjh/.virtualenvs/4ddist/lib/python3.8/site-packages/httpx/_client.py", line 1604, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/home/cjh/.virtualenvs/4ddist/lib/python3.8/site-packages/httpx/_client.py", line 1640, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "/home/cjh/.virtualenvs/4ddist/lib/python3.8/site-packages/httpx/_client.py", line 1681, in _send_single_request
    ) = await transport.handle_async_request(
  File "/home/cjh/.virtualenvs/4ddist/lib/python3.8/site-packages/httpx/_transports/default.py", line 283, in handle_async_request
    ) = await self._pool.handle_async_request(
  File "/home/cjh/.virtualenvs/4ddist/lib/python3.8/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(
  File "/home/cjh/.virtualenvs/4ddist/lib/python3.8/site-packages/httpcore/_async/connection.py", line 148, in handle_async_request
    return await self.connection.handle_async_request(
  File "/home/cjh/.virtualenvs/4ddist/lib/python3.8/site-packages/httpcore/_async/http11.py", line 122, in handle_async_request
    await self._send_request_body(stream, timeout)
  File "/home/cjh/.virtualenvs/4ddist/lib/python3.8/site-packages/httpcore/_async/http11.py", line 168, in _send_request_body
    await self._send_event(event, timeout)
  File "/home/cjh/.virtualenvs/4ddist/lib/python3.8/site-packages/httpcore/_async/http11.py", line 179, in _send_event
    bytes_to_send = self._h11_state.send(event)
  File "/home/cjh/.virtualenvs/4ddist/lib/python3.8/site-packages/h11/_connection.py", line 468, in send
    data_list = self.send_with_data_passthrough(event)
  File "/home/cjh/.virtualenvs/4ddist/lib/python3.8/site-packages/h11/_connection.py", line 501, in send_with_data_passthrough
    writer(event, data_list.append)
  File "/home/cjh/.virtualenvs/4ddist/lib/python3.8/site-packages/h11/_writers.py", line 58, in __call__
    self.send_data(event.data, write)
  File "/home/cjh/.virtualenvs/4ddist/lib/python3.8/site-packages/h11/_writers.py", line 78, in send_data
    raise LocalProtocolError("Too much data for declared Content-Length")
h11._util.LocalProtocolError: Too much data for declared Content-Length
```

**Comment by cjh1** [comment]
My issue seems to be the same as #335
