### ISSUE TITLE
Flask ResourceProtector is not compatible with Flask 2

### ISSUE THREAD

**Issue by m-aciek** [lepture/authlib#346]
**Describe the bug**

After upgrading Flask to version 2, view decorated with ResourceProtector responds with 500 instead of 401.

**Error Stacks**

```
ERROR [app:log_exception:1454]: Exception on /oauth/userinfo [GET] []
Traceback (most recent call last):
  File "my-venv/lib/python3.9/site-packages/flask/app.py", line 1718, in make_response
    rv = self.response_class.force_type(rv, request.environ)  # type: ignore  # noqa: B950
  File "my-venv/lib/python3.9/site-packages/werkzeug/wrappers/response.py", line 263, in force_type
    response = Response(*run_wsgi_app(response, environ))
  File "my-venv/lib/python3.9/site-packages/werkzeug/test.py", line 1229, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "my-venv/lib/python3.9/site-packages/werkzeug/exceptions.py", line 221, in __call__
    response = t.cast("WSGIResponse", self.get_response(environ))
  File "my-venv/lib/python3.9/site-packages/werkzeug/exceptions.py", line 209, in get_response
    headers = self.get_headers(environ, scope)
TypeError: get_headers() takes from 1 to 2 positional arguments but 3 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "my-venv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "my-venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    return self.finalize_request(rv)
  File "my-venv/lib/python3.9/site-packages/flask/app.py", line 1535, in finalize_request
    response = self.make_response(rv)
  File "my-venv/lib/python3.9/site-packages/flask/app.py", line 1720, in make_response
    raise TypeError(
  File "my-venv/lib/python3.9/site-packages/flask/app.py", line 1718, in make_response
    rv = self.response_class.force_type(rv, request.environ)  # type: ignore  # noqa: B950
  File "my-venv/lib/python3.9/site-packages/werkzeug/wrappers/response.py", line 263, in force_type
    response = Response(*run_wsgi_app(response, environ))
  File "my-venv/lib/python3.9/site-packages/werkzeug/test.py", line 1229, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "my-venv/lib/python3.9/site-packages/werkzeug/exceptions.py", line 221, in __call__
    response = t.cast("WSGIResponse", self.get_response(environ))
  File "my-venv/lib/python3.9/site-packages/werkzeug/exceptions.py", line 209, in get_response
    headers = self.get_headers(environ, scope)
TypeError: get_headers() takes from 1 to 2 positional arguments but 3 were given
The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a _HTTPException.
```

**To Reproduce**

A minimal example to reproduce the behavior:

```
from authlib.integrations.flask_oauth2 import ResourceProtector, AuthorizationServer
from authlib.oauth2.rfc6750 import BearerTokenValidator
from flask import Flask
app = Flask(__name__)


authorization = AuthorizationServer()
require_oauth = ResourceProtector()

authorization.init_app(app)
require_oauth.register_token_validator(BearerTokenValidator())


@require_oauth("scope")
def hello_world():
    return 'Hello, World!'


app.add_url_rule('/', view_func=hello_world)
```

**Expected behavior**

401 error with payload:
```
{
        "error": "missing_authorization",
        "error_description": "Missing \"Authorization\" in headers."
}
```
**Environment:**

 - Python Version: 3.9.1
 - Authlib Version: 0.15.3

**Additional context**

Flask 2 requires handling of all exceptions underneath, and expects Response or some compatible return type.

**Comment by m-aciek** [comment]
It occurs it's because of changed signatures of get_body() and get_headers() methods of HTTPException in Flask 2. Fixed in #347.

**Comment by lepture** [comment]
Fixed in master code.

**Comment by jeff-bonevich** [comment]
I am still experiencing this using Flask 2.0.1, authlib 0.15.4, python 3.7.3

**Comment by lepture** [comment]
@jeff-bonevich try the beta release: 1.0.0b1

**Comment by jeff-bonevich** [comment]
@lepture  that did it! thanks for answering a n00b :)

**Comment by azmeuk** [comment]
If 1.0.0 is not ready yet, I would suggest backporting this patch for a 0.15.5 as there is presently no workaround for this, except downgrading flask, and this is not always possible.

What do you think @lepture ?

**Comment by m-aciek** [comment]
Pull request with the back port: https://github.com/lepture/authlib/pull/371.
